### ISSUE TITLE
ATMediaFile import failure

### ISSUE THREAD

**Issue by mgogoulos** [plumi/plumi.app#1024]
**Reported by beren on 20 Jul 2007 18:43 UTC**
I downloaded Plumi and attempted an install on a clean plone instance (plython2.4/zope2.9.6/plone2.5.3) and I get the following error:
Traceback (most recent call last):
  File "c:\Zope296\Zope\lib\python\Zope2\Startup\run.py", line 56, in ?
    run()
  File "c:\Zope296\Zope\lib\python\Zope2\Startup\run.py", line 21, in run
    starter.prepare()
  File "C:\Zope296\Zope\lib\python\Zope2\Startup\__init__.py", line 98, in prepare
    self.startZope()
  File "C:\Zope296\Zope\lib\python\Zope2\Startup\__init__.py", line 257, in startZope
    Zope2.startup()
  File "C:\Zope296\Zope\lib\python\Zope2\__init__.py", line 47, in startup
    _startup()
  File "C:\Zope296\Zope\lib\python\Zope2\App\startup.py", line 103, in startup
    OFS.Application.initialize(application)
  File "C:\Zope296\Zope\lib\python\OFS\Application.py", line 304, in initialize
    initializer.initialize()
  File "C:\Zope296\Zope\lib\python\OFS\Application.py", line 333, in initialize
    self.install_products()
  File "C:\Zope296\Zope\lib\python\OFS\Application.py", line 605, in install_products
    return install_products(app)
  File "C:\Zope296\Zope\lib\python\OFS\Application.py", line 636, in install_products
    folder_permissions, raise_exc=debug_mode)
  File "C:\Zope296\Zope\lib\python\OFS\Application.py", line 783, in install_product
    initmethod(context)
  File "c:\zope-instance-conv2\Products\ATMediaFile\__init__.py", line 79, in initialize
    import tool
  File "c:\zope-instance-conv2\Products\ATMediaFile\tool\__init__.py", line 40, in ?
    import ATMediaFileTool
  File "c:\zope-instance-conv2\Products\ATMediaFile\tool\ATMediaFileTool.py", line 57, in ?
    from twisted.spread import pb
ImportError: No module named twisted.spread

Is Twisted required? Which parts? I know that 2.9.8 zope is the specified version, but I'm trying to install on Win32 and there's no installer for 2.9.8 on Win32. 

Any help would be cool!

Thanks

Beren

**Comment by mgogoulos** [comment]
**Modified by and on 23 Jul 2007 08:25 UTC**

**Comment by mgogoulos** [comment]
**Comment by andycat on 31 Jul 2007 17:54 UTC**
http://dev.plone.org/collective/changeset/46466

accompanying ATVideo enhancements:
http://dev.plone.org/collective/changeset/46467
