### ISSUE TITLE
Can't install ATVideo

### ISSUE THREAD

**Issue by mgogoulos** [plumi/plumi.app#1030]
**Reported by anonymous on 30 Aug 2007 08:57 UTC**
007-08-30 11:46:46
failed:
Traceback (most recent call last):

  File "/usr/local/Plone-2.5.3/zeocluster/client1/Products/CMFQuickInstallerTool/QuickInstallerTool.py", line 333, in installProduct
    res=install(portal)

  File "/usr/local/Plone-2.5.3/lib/python/Products/ExternalMethod/ExternalMethod.py", line 225, in __call__
    try: return f(*args, **kw)

  File "/usr/local/plone/zeocluster/Products/Plumi/ATVideo/Extensions/Install.py", line 67, in install
    quickinstaller.installProduct(dependency)

  File "/usr/local/Plone-2.5.3/zeocluster/client1/Products/CMFQuickInstallerTool/QuickInstallerTool.py", line 333, in installProduct
    res=install(portal)

  File "/usr/local/Plone-2.5.3/lib/python/Products/ExternalMethod/ExternalMethod.py", line 225, in __call__
    try: return f(*args, **kw)

  File "/usr/local/plone/zeocluster/Products/Plumi/ATMediaFile/Extensions/Install.py", line 79, in install
    portal.manage_addProduct[PROJECTNAME].manage_addTool(t)

  File "/usr/local/Plone-2.5.3/lib/python/App/FactoryDispatcher.py", line 26, in __getitem__
    return self.__bobo_traverse__(None, name)

  File "/usr/local/Plone-2.5.3/lib/python/App/FactoryDispatcher.py", line 29, in __bobo_traverse__
    product=self.aq_acquire('_getProducts')()._product(name)

  File "/usr/local/Plone-2.5.3/lib/python/App/Product.py", line 71, in _product
    def _product(self, name): return getattr(self, name)

AttributeError: ATMediaFile

**Comment by mgogoulos** [comment]
**Comment by and on 30 Aug 2007 11:20 UTC**
Hi anonymous,
are you using the tar or the latest version from svn? Please install from svn.
https://svn.plone.org/svn/collective/Plumi/trunk/

Can you give us any more details?

Also can someone confirm if this is the same bug as was fixed here?
http://plumi.org/ticket/52

**Comment by mgogoulos** [comment]
**Modified by andycat on 30 Aug 2007 15:42 UTC**
