### ISSUE TITLE
PressRoom fails to install

### ISSUE THREAD

**Issue by mgogoulos** [plumi/plumi.app#1096]
**Reported by datakid on 14 Jan 2008 05:51 UTC**
When installing on a fresh Plone installation on 

Ubuntu Gutsy (7.10),[2.5.5,[[BR]([BR]]
Plone)]
CMF-1.6.4,[(Zope 2.9.8-final, python 2.4.4, linux2),[[BR]([BR]]
Zope)]
Five 1.4.2,[2.4.4 (#1, Jan 14 2008, 14:42:50) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]([BR]]
Python),[1.1.6[[BR]([BR]]
PIL)]

(ie, the Plone 2.5.5 unified installer)

and the trunk of the plumi svn.

Here is the output:

```
2008-01-14 15:42:41
failed:
Traceback (most recent call last):

  File "/opt/Plone-2.5.5/zeocluster/client1/Products/CMFQuickInstallerTool/QuickInstallerTool.py", line 333, in installProduct
    res=install(portal)

  File "/opt/Plone-2.5.5/lib/python/Products/ExternalMethod/ExternalMethod.py", line 225, in __call__
    try: return f(*args, **kw)

  File "/opt/plumi_trunk/PressRoom/Extensions/Install.py", line 90, in install
    kupuTool.updateResourceTypes(({'resource_type' : 'linkable',

  File "/opt/Plone-2.5.5/zeocluster/client1/Products/kupu/plone/librarytool.py", line 159, in updateResourceTypes
    portal_types = self._validate_portal_types(resource_type, type['portal_types'])

  File "/opt/Plone-2.5.5/zeocluster/client1/Products/kupu/plone/librarytool.py", line 146, in _validate_portal_types
    raise KupuError, "Resource type: %s, invalid type: %s" % (resource_type, p)

KupuError: Resource type: linkable, invalid type: CallOut
```

**Comment by mgogoulos** [comment]
**Comment by datakid on 14 Jan 2008 09:31 UTC**
After doing some searching online, I discovered that you could get it to install if you  comment out part of the function (?) "def install(self)" in /opt/plumi_trunk/PressRoom/Extensions/Install.py 
The diff is below

I read about that [http://www.nabble.com/RE:-Can't-install-SignupSheet-on-Zope-2.9---Plone-2.5.2-p11020529s21655.html](here)


```

--- Install.py	(revision 56843)
+++ Install.py	(working copy)
@@ -87,15 +87,15 @@
 
     # kupu_library_tool has an odd interface, basically written purely to
     # work with its configuration page. :-(
-    kupuTool.updateResourceTypes(({'resource_type' : 'linkable',
-                                   'old_type'      : 'linkable',
-                                   'portal_types'  :  linkable},
-                                  {'resource_type' : 'mediaobject',
-                                   'old_type'      : 'mediaobject',
-                                   'portal_types'  :  mediaobject},
-                                  {'resource_type' : 'collection',
-                                   'old_type'      : 'collection',
-                                   'portal_types'  :  collection},))
+#    kupuTool.updateResourceTypes(({'resource_type' : 'linkable',
+#                                   'old_type'      : 'linkable',
+#                                   'portal_types'  :  linkable},
+#                                  {'resource_type' : 'mediaobject',
+#                                   'old_type'      : 'mediaobject',
+#                                   'portal_types'  :  mediaobject},
+#                                  {'resource_type' : 'collection',
+#                                   'old_type'      : 'collection',
+#                                   'portal_types'  :  collection},))
     print >> out, "Added PressRoom types to kupu's linkable types, PressRoom type to collection"
     
     # enable two indices to be used by smart folders
```

When I look at the local site http://localhost:8080/plumi-test/kupu_library_tool/zmi_resource_types (on my machine) I see 4 Resource types, yet in the code I commented out, I only see 3 - the type "media" is missing?

**Comment by mgogoulos** [comment]
**Comment by datakid on 14 Jan 2008 09:44 UTC**
Note that doing this means you can successfully "publish a callout" in that it installs, doesn't fail when you add one, appears in the member's call out's folder...but does not appear in the callouts portlet on the home page ("Recent callouts")

**Comment by mgogoulos** [comment]
**Comment by datakid on 16 Jan 2008 01:22 UTC**
This has been fixed, closing.

I went to find the changeset, but it was difficult - I don't quite understand that part yet. I would seem that we are different from the dev.plone.org changeset I found here: http://dev.plone.org/collective/browser/ATVideo/trunk

**Comment by mgogoulos** [comment]
**Comment by datakid on 16 Jan 2008 01:27 UTC**
Ok, I found _a_ changeset, but it's outta date http://dev.plone.org/collective/browser/ATVideo/branches/engage/Extensions
