### ISSUE TITLE
Plumi-0.2 breaks Plone

### ISSUE THREAD

**Issue by mgogoulos** [plumi/plumi.app#1106]
**Reported by datakid on 9 Feb 2008 00:38 UTC**
I tried testing the new bz2 that was released yesterday.

Plone works fine. Add the 
```
products /path/to/plumi
```

to zope.conf, restart the zope cluster and it fails to add a new site with the following error:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 115, in publish
  Module ZPublisher.mapply, line 88, in mapply
  Module ZPublisher.Publish, line 41, in call_object
  Module Products.CMFPlone.factory, line 52, in addPloneSite
  Module Products.GenericSetup.tool, line 252, in runAllImportSteps
   - __traceback_info__: profile-CMFPlone:plone
  Module Products.GenericSetup.tool, line 766, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 732, in _doRunImportStep
   - __traceback_info__: plone_various
  Module Products.CMFPlone.setuphandlers, line 202, in importVarious
  Module Products.CMFPlone.setuphandlers, line 41, in installProducts
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 330, in installProduct
   - __traceback_info__: ('ATContentTypes',)
  Module Products.ExternalMethod.ExternalMethod, line 225, in __call__
   - __traceback_info__: ((<PloneSite at /atest>,), {'reinstall': False}, None)
  Module /opt/Plone-2.5.5/zeocluster/client1/Products/ATContentTypes/Extensions/Install.py, line 90, in install
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 333, in installProduct
   - __traceback_info__: ('ATReferenceBrowserWidget',)
  Module Products.ExternalMethod.ExternalMethod, line 225, in __call__
   - __traceback_info__: ((<PloneSite at /atest>,), {}, None)
  Module /opt/Plone-2.5.5/zeocluster/client1/Products/ATReferenceBrowserWidget/Extensions/Install.py, line 15, in install
AttributeError: site_properties
```

Using Plone-2.5.5 from the unified installer.

**Comment by mgogoulos** [comment]
**Comment by datakid on 9 Feb 2008 00:41 UTC**
When trying to view a plone-site added before adding the new Products directory, we get this error:

```
Site Error

An error was encountered while publishing this resource.

AttributeError
Sorry, a site error occurred.

Traceback (innermost last):

    * Module ZPublisher.Publish, line 196, in publish_module_standard
    * Module Products.PlacelessTranslationService.PatchStringIO, line 34, in new_publish
    * Module ZPublisher.Publish, line 146, in publish
    * Module Zope2.App.startup, line 222, in zpublisher_exception_hook
    * Module ZPublisher.Publish, line 115, in publish
    * Module ZPublisher.mapply, line 88, in mapply
    * Module ZPublisher.Publish, line 41, in call_object
    * Module Shared.DC.Scripts.Bindings, line 311, in __call__
    * Module Shared.DC.Scripts.Bindings, line 348, in _bindAndExec
    * Module Products.CMFCore.FSPageTemplate, line 195, in _exec
    * Module Products.CacheSetup.patch_cmf, line 18, in FSPT_pt_render
    * Module Products.CacheSetup.patch_utils, line 9, in call_pattern
    * Module Products.CMFCore.FSPageTemplate, line 134, in pt_render
    * Module Products.CacheSetup.patch_cmf, line 68, in PT_pt_render
    * Module Products.CacheSetup.patch_utils, line 9, in call_pattern
    * Module Products.PageTemplates.PageTemplate, line 104, in pt_render
      <FSPageTemplate at /test/document_view used for /test/front-page>
    * Module TAL.TALInterpreter, line 238, in __call__
    * Module TAL.TALInterpreter, line 281, in interpret
    * Module TAL.TALInterpreter, line 749, in do_useMacro
    * Module TAL.TALInterpreter, line 281, in interpret
    * Module TAL.TALInterpreter, line 457, in do_optTag_tal
    * Module TAL.TALInterpreter, line 442, in do_optTag
    * Module TAL.TALInterpreter, line 437, in no_tag
    * Module TAL.TALInterpreter, line 281, in interpret
    * Module TAL.TALInterpreter, line 749, in do_useMacro
    * Module TAL.TALInterpreter, line 281, in interpret
    * Module TAL.TALInterpreter, line 511, in do_setGlobal_tal
    * Module Products.PageTemplates.TALES, line 221, in evaluate
      URL: file:CMFPlone/skins/plone_templates/global_defines.pt
      Line 3, Column 0
      Expression: standard:'context/@@plone'
      Names:

      {'container': <PloneSite at /test>,
       'context': <ATDocument at /test/front-page>,
       'default': <Products.PageTemplates.TALES.Default instance at 0xb7095d4c>,
       'here': <ATDocument at /test/front-page>,
       'loop': <Products.PageTemplates.TALES.SafeMapping object at 0xbb1914c>,
       'modules': <Products.PageTemplates.ZRPythonExpr._SecureModuleImporter instance at 0xb709c06c>,
       'nothing': None,
       'options': {'args': ()},
       'repeat': <Products.PageTemplates.TALES.SafeMapping object at 0xbb1914c>,
       'request': <HTTPRequest, URL=http://localhost:8080/test/front-page/document_view>,
       'root': <Application at >,
       'template': <FSPageTemplate at /test/document_view used for /test/front-page>,
       'traverse_subpath': [      'user': <PropertiedUser 'admin'>}

    * Module Products.PageTemplates.Expressions, line 185, in __call__
    * Module Products.PageTemplates.Expressions, line 173, in _eval
    * Module Products.PageTemplates.Expressions, line 127, in _eval
      __traceback_info__: context
    * Module Products.PageTemplates.Expressions, line 286, in restrictedTraverse
      __traceback_info__: {'path': ['@@plone'](],
), 'TraversalRequestNameStack': []}
    * Module Products.Archetypes.BaseObject, line 1138, in __bobo_traverse__

AttributeError: @@plone (Also, the following error occurred while attempting to render the standard error message, please see the event log for full details: @@plone)
```

**Comment by mgogoulos** [comment]
**Comment by datakid on 9 Feb 2008 01:02 UTC**
When I start in debug mode I get this:

```
musicman@boxen:/opt/Plone-2.5.5/zeocluster/client1/bin$ sudo ./runzope -X debug-mode=on
2008-02-09 12:00:56 INFO ZServer HTTP server started at Sat Feb  9 12:00:56 2008
        Hostname: 0.0.0.0
        Port: 8080
2008-02-09 12:00:56 INFO Zope Set effective user to "plone"
2008-02-09 12:00:58 WARNING Init Class Products.CMFFormController.ControllerBase.ControllerBase has a security declaration for nonexistent method 'getPostRequired'
2008-02-09 12:00:58 INFO ATMediaFile Installing Product
/opt/plumi-0.2-final/ATMediaFile/__init__.py:54: DeprecationWarning: The module, 'Products.CMFCore.CMFCorePermissions' is a deprecated compatiblity alias for 'Products.CMFCore.permissions';  please use the new module instead.
  from Products.CMFCore import CMFCorePermissions
/opt/plumi-0.2-final/ATMediaFile/__init__.py:56: DeprecationWarning: PloneUtilities is deprecated and will be removed in Plone 3.0, please import from Products.CMFPlone.utils instead.
  from Products.CMFPlone.PloneUtilities import ToolInit
2008-02-09 12:00:59 INFO ATVideo Installing Product
2008-02-09 12:00:59 INFO PlacelessTranslationService Applying patch 
*** Patching ZPublisher.Publish with the get_request patch! ***
2008-02-09 12:00:59 ERROR Zope Could not import Products.ATVideo
Traceback (most recent call last):
  File "/opt/Plone-2.5.5/lib/python/OFS/Application.py", line 708, in import_product
    product=__import__(pname, global_dict, global_dict, silly)
  File "/opt/plumi-0.2-final/ATVideo/__init__.py", line 75, in ?
    from Products.ATVocabularyManager.namedvocabulary import NamedVocabulary
  File "/opt/plumi-0.2-final/ATVocabularyManager/__init__.py", line 13, in ?
    from Products.ATVocabularyManager.namedvocabulary import NamedVocabulary
  File "/opt/plumi-0.2-final/ATVocabularyManager/namedvocabulary.py", line 19, in ?
    from Products.ATVocabularyManager.types.tree.vocabulary import TreeVocabulary
  File "/opt/plumi-0.2-final/ATVocabularyManager/types/__init__.py", line 3, in ?
    from Products.ATVocabularyManager.types import vdex
  File "/opt/plumi-0.2-final/ATVocabularyManager/types/vdex/__init__.py", line 1, in ?
    from Products.ATVocabularyManager.types.vdex.vocabularyxml import IMSVDEXVocabulary
  File "/opt/plumi-0.2-final/ATVocabularyManager/types/vdex/vocabularyxml.py", line 27, in ?
    from imsvdex.vdex import VDEXManager, VDEXError
ImportError: No module named imsvdex.vdex
Traceback (most recent call last):
  File "/opt/Plone-2.5.5/lib/python/Zope2/Startup/run.py", line 56, in ?
    run()
  File "/opt/Plone-2.5.5/lib/python/Zope2/Startup/run.py", line 21, in run
    starter.prepare()
  File "/opt/Plone-2.5.5/lib/python/Zope2/Startup/__init__.py", line 98, in prepare
    self.startZope()
  File "/opt/Plone-2.5.5/lib/python/Zope2/Startup/__init__.py", line 257, in startZope
    Zope2.startup()
  File "/opt/Plone-2.5.5/lib/python/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/opt/Plone-2.5.5/lib/python/Zope2/App/startup.py", line 46, in startup
    OFS.Application.import_products()
  File "/opt/Plone-2.5.5/lib/python/OFS/Application.py", line 685, in import_products
    import_product(product_dir, product_name, raise_exc=debug_mode)
  File "/opt/Plone-2.5.5/lib/python/OFS/Application.py", line 723, in import_product
    raise sys.exc_info()
KeyError

```

**Comment by mgogoulos** [comment]
**Comment by datakid on 9 Feb 2008 01:08 UTC**
and seeing the imsvdex error, I've run:

```
musicman@boxen:/opt/Plone-2.5.5/Python-2.4.4$ sudo easy_install-2.4 imsvdex
Searching for imsvdex
Best match: imsvdex 1.0-beta
Processing imsvdex-1.0_beta-py2.4.egg
imsvdex 1.0-beta is already the active version in easy-install.pth

Using /usr/lib/python2.4/site-packages/imsvdex-1.0_beta-py2.4.egg
Processing dependencies for imsvdex
Finished processing dependencies for imsvdex
```

**Comment by mgogoulos** [comment]
**Comment by datakid on 9 Feb 2008 02:03 UTC**
damn, that's murder.

remember kids - always run easy_install local to where you want it:
```
/opt/Plone-2.5.5/Python-2.4.4$ sudo easy_install-2.4 imsvdex
```

is a different command to 
```
/opt/Plone-2.5.5/Python-2.4.4$ sudo ./easy_install-2.4 imsvdex
```
