### ISSUE TITLE
"Plone Site" fails with trunk

### ISSUE THREAD

**Issue by mgogoulos** [plumi/plumi.app#1118]
**Reported by denis on 3 Nov 2008 12:45 UTC**
I had tried the trunk following this doc (http://plumi.org/wiki/HowToInstallPlumiSVN)

But it was impossible to add a "Plone Site"

The error was 

```

Site Error

An error was encountered while publishing this resource.

Error Type: AttributeError
Error Value: site_properties
```

And the log

```
2008-11-03T13:25:39 INFO ZEO.zrpc.Connection(S) (127.0.0.1:32926) loadEx() raised exception: 0x2709
Traceback (most recent call last):
  File "/opt/Plone-2.5.5/lib/python/ZEO/zrpc/connection.py", line 421, in handle_request
    ret = meth(*args)
  File "/opt/Plone-2.5.5/lib/python/ZEO/StorageServer.py", line 248, in loadEx
    return self.storage.loadEx(oid, version)
  File "/opt/Plone-2.5.5/lib/python/ZODB/FileStorage/FileStorage.py", line 523, in loadEx
    pos = self._lookup_pos(oid)
  File "/opt/Plone-2.5.5/lib/python/ZODB/FileStorage/FileStorage.py", line 514, in _lookup_pos
    raise POSKeyError(oid)
POSKeyError: 0x2709
------
2008-11-03T13:25:39 INFO ZEO.zrpc.Connection(S) (127.0.0.1:32926) loadEx() raised exception: 0x26d5
Traceback (most recent call last):
  File "/opt/Plone-2.5.5/lib/python/ZEO/zrpc/connection.py", line 421, in handle_request
    ret = meth(*args)
  File "/opt/Plone-2.5.5/lib/python/ZEO/StorageServer.py", line 248, in loadEx
    return self.storage.loadEx(oid, version)
  File "/opt/Plone-2.5.5/lib/python/ZODB/FileStorage/FileStorage.py", line 523, in loadEx
    pos = self._lookup_pos(oid)
  File "/opt/Plone-2.5.5/lib/python/ZODB/FileStorage/FileStorage.py", line 514, in _lookup_pos
    raise POSKeyError(oid)
POSKeyError: 0x26d5
```

**Comment by mgogoulos** [comment]
**Comment by andycat on 4 Nov 2008 01:08 UTC**
hey

The trunk of Plumi, at the moment, targets Plone 3.x only.

If you want to use plone 2.5.5 , you should keep using plumi 0.2.1-final or the latest tag for 0.2.2 , which is plumi 0.2.2-rc5
Also, if you want to do development on plumi 0.2.x / plone 2.5.5 you should use the branch 'plumi-0.2.x' of Plumi.

Ive upated the wiki page about this - see step 5 : http://plumi.org/wiki/HowToInstallPlumiSVN

Ive also upated the wiki page on installing from the 0.2-final to 0.2.1-final version - I updated it to use plumi 0.2.1-final. see : http://plumi.org/wiki/HowToInstallPlumi
