### ISSUE TITLE
Assertion error in plumi buildout on Ubuntu

### ISSUE THREAD

**Issue by mgogoulos** [plumi/plumi.app#1130]
**Reported by datakid on 25 Nov 2008 06:25 UTC**
```
engage@rosebud:/opt/plumi-buildout$ sudo ./bin/buildout 
Installing plone.
Installing zope2.
running build_ext
creating zope.proxy
copying zope/proxy/proxy.h -> zope.proxy
building 'AccessControl.cAccessControl' extension
creating build
creating build/temp.linux-i686-2.4
creating build/temp.linux-i686-2.4/AccessControl
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -IExtensionClass -I. -IAcquisition -I/usr/include/python2.4 -c AccessControl/cAccessControl.c -o build/temp.linux-i686-2.4/AccessControl/cAccessControl.o
In file included from AccessControl/cAccessControl.c:51:
./ExtensionClass/ExtensionClass.h:83:20: error: Python.h: No such file or directory
./ExtensionClass/ExtensionClass.h:84:20: error: import.h: No such file or directory
In file included from AccessControl/cAccessControl.c:51:
./ExtensionClass/ExtensionClass.h:95: error: expected specifier-qualifier-list before PyObject_HEAD
./ExtensionClass/ExtensionClass.h:108: error: expected specifier-qualifier-list before PyObject
./ExtensionClass/ExtensionClass.h:114: error: NULL undeclared here (not in a function)
In file included from AccessControl/cAccessControl.c:52:
./Acquisition/Acquisition.h:19: error: expected specifier-qualifier-list before PyObject
AccessControl/cAccessControl.c:59: error: expected ) before * token
AccessControl/cAccessControl.c:69: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:83: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:91: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:107: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:128: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:151: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:176: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:205: error: expected ) before * token
AccessControl/cAccessControl.c:222: error: expected ) before * token
AccessControl/cAccessControl.c:240: error: expected ) before * token
AccessControl/cAccessControl.c:259: error: expected ) before * token
AccessControl/cAccessControl.c:280: error: expected ) before * token
AccessControl/cAccessControl.c:308: error: expected specifier-qualifier-list before PyObject_HEAD
AccessControl/cAccessControl.c:312: error: expected specifier-qualifier-list before PyObject_HEAD
AccessControl/cAccessControl.c:321: error: expected specifier-qualifier-list before PyObject_HEAD
AccessControl/cAccessControl.c:328: error: expected specifier-qualifier-list before PyObject_HEAD
AccessControl/cAccessControl.c:339: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:343: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:344: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:345: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:349: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:351: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:353: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:357: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:358: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:359: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:360: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:361: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:364: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:366: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:368: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:370: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:373: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:376: error: expected declaration specifiers or ... before PyObject
AccessControl/cAccessControl.c:376: error: expected declaration specifiers or ... before PyObject
AccessControl/cAccessControl.c:378: error: expected =, ,, ;, asm or __attribute__ before ExtensionClassGetattro
AccessControl/cAccessControl.c:385: error: expected =, ,, ;, asm or __attribute__ before cAccessControl_methods
AccessControl/cAccessControl.c:411: error: expected =, ,, ;, asm or __attribute__ before ZopeSecurityPolicy_methods
AccessControl/cAccessControl.c:420: error: expected =, ,, ;, asm or __attribute__ before ZopeSecurityPolicyType
AccessControl/cAccessControl.c:460: error: expected =, ,, ;, asm or __attribute__ before SecurityManager_methods
AccessControl/cAccessControl.c:479: error: expected =, ,, ;, asm or __attribute__ before SecurityManagerType
AccessControl/cAccessControl.c:519: error: expected =, ,, ;, asm or __attribute__ before PermissionRole_methods
AccessControl/cAccessControl.c:538: error: expected =, ,, ;, asm or __attribute__ before PermissionRoleType
AccessControl/cAccessControl.c:581: error: expected =, ,, ;, asm or __attribute__ before imPermissionRole_methods
AccessControl/cAccessControl.c:595: error: expected =, ,, ;, asm or __attribute__ before imSequenceMethods
AccessControl/cAccessControl.c:608: error: expected =, ,, ;, asm or __attribute__ before imPermissionRoleType
AccessControl/cAccessControl.c:651: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:652: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:653: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:654: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:655: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:656: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:657: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:658: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:659: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:660: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:661: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:662: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:663: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:664: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:665: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:666: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:667: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:668: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:669: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:670: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:671: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:672: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:673: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:674: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:675: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:676: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:677: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:678: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:679: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:680: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c: In function ZopeSecurityPolicy_setup:
AccessControl/cAccessControl.c:698: error: NoSequenceFormat undeclared (first use in this function)
AccessControl/cAccessControl.c:698: error: (Each undeclared identifier is reported only once
AccessControl/cAccessControl.c:698: error: for each function it appears in.)
AccessControl/cAccessControl.c:698: warning: implicit declaration of function PyString_FromString
AccessControl/cAccessControl.c:703: error: defaultPermission undeclared (first use in this function)
AccessControl/cAccessControl.c:703: warning: implicit declaration of function Py_BuildValue
AccessControl/cAccessControl.c:704: error: _what_not_even_god_should_do undeclared (first use in this function)
AccessControl/cAccessControl.c:705: error: __roles__ undeclared (first use in this function)
AccessControl/cAccessControl.c:706: error: __of__ undeclared (first use in this function)
AccessControl/cAccessControl.c:707: error: Anonymous undeclared (first use in this function)
AccessControl/cAccessControl.c:708: error: AnonymousTuple undeclared (first use in this function)
AccessControl/cAccessControl.c:709: error: ManagerTuple undeclared (first use in this function)
AccessControl/cAccessControl.c:710: error: stack_str undeclared (first use in this function)
AccessControl/cAccessControl.c:711: error: user_str undeclared (first use in this function)
AccessControl/cAccessControl.c:712: error: validate_str undeclared (first use in this function)
AccessControl/cAccessControl.c:713: error: _proxy_roles_str undeclared (first use in this function)
AccessControl/cAccessControl.c:715: error: allowed_str undeclared (first use in this function)
AccessControl/cAccessControl.c:716: error: getOwner_str undeclared (first use in this function)
AccessControl/cAccessControl.c:717: error: getWrappedOwner_str undeclared (first use in this function)
AccessControl/cAccessControl.c:719: error: getPhysicalRoot_str undeclared (first use in this function)
AccessControl/cAccessControl.c:721: error: aq_parent_str undeclared (first use in this function)
AccessControl/cAccessControl.c:722: error: _check_context_str undeclared (first use in this function)
AccessControl/cAccessControl.c:724: error: unrestrictedTraverse_str undeclared (first use in this function)
AccessControl/cAccessControl.c:728: error: checkPermission_str undeclared (first use in this function)
AccessControl/cAccessControl.c:730: error: __allow_access_to_unprotected_subobjects__ undeclared (first use in this function)
AccessControl/cAccessControl.c: At top level:
AccessControl/cAccessControl.c:744: error: expected ) before * token
AccessControl/cAccessControl.c:759: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c: In function ZopeSecurityPolicy_dealloc:
AccessControl/cAccessControl.c:1282: warning: implicit declaration of function Py_DECREF
AccessControl/cAccessControl.c:1282: error: ZopeSecurityPolicy has no member named ob_type
AccessControl/cAccessControl.c:1283: error: ZopeSecurityPolicy has no member named ob_type
AccessControl/cAccessControl.c:1283: error: Py_TPFLAGS_HAVE_CLASS undeclared (first use in this function)
AccessControl/cAccessControl.c:1283: error: ZopeSecurityPolicy has no member named ob_type
AccessControl/cAccessControl.c:1283: error: ZopeSecurityPolicy has no member named ob_type
AccessControl/cAccessControl.c:1283: error: PyObject undeclared (first use in this function)
AccessControl/cAccessControl.c:1283: error: expected expression before ) token
AccessControl/cAccessControl.c:1283: warning: implicit declaration of function PyObject_FREE
AccessControl/cAccessControl.c: At top level:
AccessControl/cAccessControl.c:1303: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:1323: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:1340: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c: In function SecurityManager_dealloc:
AccessControl/cAccessControl.c:1361: warning: implicit declaration of function Py_XDECREF
AccessControl/cAccessControl.c:1361: error: SecurityManager has no member named thread_id
AccessControl/cAccessControl.c:1362: error: SecurityManager has no member named context
AccessControl/cAccessControl.c:1363: error: SecurityManager has no member named policy
AccessControl/cAccessControl.c:1364: error: SecurityManager has no member named validate
AccessControl/cAccessControl.c:1365: error: SecurityManager has no member named checkPermission
AccessControl/cAccessControl.c:1366: error: SecurityManager has no member named ob_type
AccessControl/cAccessControl.c:1367: error: SecurityManager has no member named ob_type
AccessControl/cAccessControl.c:1367: error: Py_TPFLAGS_HAVE_CLASS undeclared (first use in this function)
AccessControl/cAccessControl.c:1367: error: SecurityManager has no member named ob_type
AccessControl/cAccessControl.c:1367: error: SecurityManager has no member named ob_type
AccessControl/cAccessControl.c:1367: error: PyObject undeclared (first use in this function)
AccessControl/cAccessControl.c:1367: error: expected expression before ) token
AccessControl/cAccessControl.c: At top level:
AccessControl/cAccessControl.c:1370: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:1399: error: expected declaration specifiers or ... before PyObject
AccessControl/cAccessControl.c:1399: error: expected declaration specifiers or ... before PyObject
AccessControl/cAccessControl.c: In function SecurityManager_setattro:
AccessControl/cAccessControl.c:1401: warning: implicit declaration of function PyString_Check
AccessControl/cAccessControl.c:1401: error: name undeclared (first use in this function)
AccessControl/cAccessControl.c:1401: warning: implicit declaration of function PyUnicode_Check
AccessControl/cAccessControl.c:1402: warning: implicit declaration of function PyString_AsString
AccessControl/cAccessControl.c:1402: warning: initialization makes pointer from integer without a cast
AccessControl/cAccessControl.c:1409: warning: implicit declaration of function strcmp
AccessControl/cAccessControl.c:1411: warning: implicit declaration of function Py_INCREF
AccessControl/cAccessControl.c:1411: error: v undeclared (first use in this function)
AccessControl/cAccessControl.c:1412: warning: implicit declaration of function PyVar_Assign
AccessControl/cAccessControl.c:1412: error: SecurityManager has no member named thread_id
AccessControl/cAccessControl.c:1418: error: SecurityManager has no member named context
AccessControl/cAccessControl.c:1424: error: SecurityManager has no member named policy
AccessControl/cAccessControl.c:1425: error: SecurityManager has no member named validate
AccessControl/cAccessControl.c:1427: error: SecurityManager has no member named validate
AccessControl/cAccessControl.c:1428: error: SecurityManager has no member named validate
AccessControl/cAccessControl.c:1430: error: SecurityManager has no member named checkPermission
AccessControl/cAccessControl.c:1432: error: SecurityManager has no member named checkPermission
AccessControl/cAccessControl.c:1433: error: SecurityManager has no member named checkPermission
AccessControl/cAccessControl.c:1440: warning: implicit declaration of function PyErr_SetObject
AccessControl/cAccessControl.c:1440: error: PyExc_AttributeError undeclared (first use in this function)
AccessControl/cAccessControl.c: At top level:
AccessControl/cAccessControl.c:1452: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:1482: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:1541: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c: In function PermissionRole_dealloc:
AccessControl/cAccessControl.c:1556: error: PermissionRole has no member named __name__
AccessControl/cAccessControl.c:1558: error: PermissionRole has no member named _p
AccessControl/cAccessControl.c:1560: error: PermissionRole has no member named __roles__
AccessControl/cAccessControl.c:1562: error: PermissionRole has no member named ob_type
AccessControl/cAccessControl.c:1564: error: PermissionRole has no member named ob_type
AccessControl/cAccessControl.c:1564: error: Py_TPFLAGS_HAVE_CLASS undeclared (first use in this function)
AccessControl/cAccessControl.c:1564: error: PermissionRole has no member named ob_type
AccessControl/cAccessControl.c:1564: error: PermissionRole has no member named ob_type
AccessControl/cAccessControl.c:1564: error: PyObject undeclared (first use in this function)
AccessControl/cAccessControl.c:1564: error: expected expression before ) token
AccessControl/cAccessControl.c: At top level:
AccessControl/cAccessControl.c:1574: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:1610: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c: In function imPermissionRole_length:
AccessControl/cAccessControl.c:1621: error: PyObject undeclared (first use in this function)
AccessControl/cAccessControl.c:1621: error: v undeclared (first use in this function)
AccessControl/cAccessControl.c:1622: error: pa undeclared (first use in this function)
AccessControl/cAccessControl.c:1634: error: imPermissionRole has no member named _v
AccessControl/cAccessControl.c:1636: error: imPermissionRole has no member named _pa
AccessControl/cAccessControl.c:1638: warning: implicit declaration of function PyErr_SetString
AccessControl/cAccessControl.c:1638: error: PyExc_AttributeError undeclared (first use in this function)
AccessControl/cAccessControl.c:1641: warning: implicit declaration of function callmethod1
AccessControl/cAccessControl.c:1641: error: expected expression before ) token
AccessControl/cAccessControl.c:1641: error: __of__ undeclared (first use in this function)
AccessControl/cAccessControl.c:1644: error: imPermissionRole has no member named _v
AccessControl/cAccessControl.c:1646: error: imPermissionRole has no member named _pa
AccessControl/cAccessControl.c:1649: warning: implicit declaration of function PyObject_Length
AccessControl/cAccessControl.c: At top level:
AccessControl/cAccessControl.c:1658: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c: In function imPermissionRole_dealloc:
AccessControl/cAccessControl.c:1700: error: imPermissionRole has no member named _p
AccessControl/cAccessControl.c:1702: error: imPermissionRole has no member named _pa
AccessControl/cAccessControl.c:1704: error: imPermissionRole has no member named __roles__
AccessControl/cAccessControl.c:1706: error: imPermissionRole has no member named _v
AccessControl/cAccessControl.c:1708: error: imPermissionRole has no member named ob_type
AccessControl/cAccessControl.c:1710: error: imPermissionRole has no member named ob_type
AccessControl/cAccessControl.c:1710: error: Py_TPFLAGS_HAVE_CLASS undeclared (first use in this function)
AccessControl/cAccessControl.c:1710: error: imPermissionRole has no member named ob_type
AccessControl/cAccessControl.c:1710: error: imPermissionRole has no member named ob_type
AccessControl/cAccessControl.c:1710: error: PyObject undeclared (first use in this function)
AccessControl/cAccessControl.c:1710: error: expected expression before ) token
AccessControl/cAccessControl.c: At top level:
AccessControl/cAccessControl.c:1717: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:1739: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:1943: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:1981: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:2128: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:2152: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:2162: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:2186: error: expected =, ,, ;, asm or __attribute__ before * token
AccessControl/cAccessControl.c:2212: error: array type has incomplete element type
AccessControl/cAccessControl.c:2213: error: PyCFunction undeclared here (not in a function)
AccessControl/cAccessControl.c:2213: error: expected } before dtml_guarded_getattr
AccessControl/cAccessControl.c: In function initcAccessControl:
AccessControl/cAccessControl.c:2227: error: PyObject undeclared (first use in this function)
AccessControl/cAccessControl.c:2227: error: module undeclared (first use in this function)
AccessControl/cAccessControl.c:2228: error: dict undeclared (first use in this function)
AccessControl/cAccessControl.c:2232: error: expected =, ,, ;, asm or __attribute__ before RestrictedDTMLMixinType
AccessControl/cAccessControl.c:2232: error: RestrictedDTMLMixinType undeclared (first use in this function)
AccessControl/cAccessControl.c:2229: error: expected expression before { token
AccessControl/cAccessControl.c:2234: warning: implicit declaration of function PyCObject_Import
AccessControl/cAccessControl.c:2234: warning: assignment makes pointer from integer without a cast
AccessControl/cAccessControl.c:2238: error: ExtensionClassGetattro undeclared (first use in this function)
AccessControl/cAccessControl.c:2238: error: struct ExtensionClassCAPIstruct has no member named ECBaseType_
AccessControl/cAccessControl.c:2240: warning: implicit declaration of function Py_InitModule3
AccessControl/cAccessControl.c:2241: error: cAccessControl_methods undeclared (first use in this function)
AccessControl/cAccessControl.c:2244: error: api undeclared (first use in this function)
AccessControl/cAccessControl.c:2244: warning: implicit declaration of function PyImport_ImportModule
AccessControl/cAccessControl.c:2244: warning: implicit declaration of function PyObject_GetAttrString
AccessControl/cAccessControl.c:2244: warning: implicit declaration of function PyCObject_AsVoidPtr
AccessControl/cAccessControl.c:2244: warning: assignment makes pointer from integer without a cast
AccessControl/cAccessControl.c:2247: warning: implicit declaration of function PyModule_GetDict
AccessControl/cAccessControl.c:2249: warning: implicit declaration of function PyDict_SetItemString
AccessControl/cAccessControl.c:2250: error: _what_not_even_god_should_do undeclared (first use in this function)
AccessControl/cAccessControl.c:2252: warning: assignment makes pointer from integer without a cast
AccessControl/cAccessControl.c:2252: error: struct ExtensionClassCAPIstruct has no member named PyExtensionClass_Export_
AccessControl/cAccessControl.c:2255: warning: assignment makes pointer from integer without a cast
AccessControl/cAccessControl.c:2255: error: struct ExtensionClassCAPIstruct has no member named PyExtensionClass_Export_
AccessControl/cAccessControl.c:2255: error: ZopeSecurityPolicyType undeclared (first use in this function)
AccessControl/cAccessControl.c:2258: warning: assignment makes pointer from integer without a cast
AccessControl/cAccessControl.c:2258: error: struct ExtensionClassCAPIstruct has no member named PyExtensionClass_Export_
AccessControl/cAccessControl.c:2258: error: SecurityManagerType undeclared (first use in this function)
AccessControl/cAccessControl.c:2261: warning: assignment makes pointer from integer without a cast
AccessControl/cAccessControl.c:2261: error: struct ExtensionClassCAPIstruct has no member named PyExtensionClass_Export_
AccessControl/cAccessControl.c:2261: error: PermissionRoleType undeclared (first use in this function)
AccessControl/cAccessControl.c:2264: warning: assignment makes pointer from integer without a cast
AccessControl/cAccessControl.c:2264: error: struct ExtensionClassCAPIstruct has no member named PyExtensionClass_Export_
AccessControl/cAccessControl.c:2264: error: imPermissionRoleType undeclared (first use in this function)
AccessControl/cAccessControl.c:2267: error: imPermissionRoleObj undeclared (first use in this function)
AccessControl/cAccessControl.c:2267: warning: implicit declaration of function PyMapping_GetItemString
AccessControl/cAccessControl.c:2270: error: aq_validate undeclared (first use in this function)
AccessControl/cAccessControl.c:2276: error: Containers undeclared (first use in this function)
AccessControl/cAccessControl.c:2277: error: ContainerAssertions undeclared (first use in this function)
AccessControl/cAccessControl.c:2286: error: getRoles undeclared (first use in this function)
AccessControl/cAccessControl.c:2295: error: Unauthorized undeclared (first use in this function)
AccessControl/cAccessControl.c:2303: error: getSecurityManager undeclared (first use in this function)
AccessControl/cAccessControl.c:2311: error: LOG undeclared (first use in this function)
AccessControl/cAccessControl.c:2312: error: PROBLEM undeclared (first use in this function)
error: command 'gcc' failed with exit status 1
While:
  Installing zope2.

An internal error occured due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/tmp/tmpspsTwb/zc.buildout-1.1.1-py2.5.egg/zc/buildout/buildout.py", line 1477, in main
  File "/tmp/tmpspsTwb/zc.buildout-1.1.1-py2.5.egg/zc/buildout/buildout.py", line 462, in install
  File "/tmp/tmpspsTwb/zc.buildout-1.1.1-py2.5.egg/zc/buildout/buildout.py", line 1060, in _call
  File "/opt/plumi-buildout/eggs/plone.recipe.zope2install-2.5-py2.5.egg/plone/recipe/zope2install/__init__.py", line 153, in install
    ) == 0
AssertionError
```

**Comment by mgogoulos** [comment]
**Comment by datakid on 25 Nov 2008 06:26 UTC**
does plumi _require_ python2.4?

I seem to remember that it does...

**Comment by mgogoulos** [comment]
**Comment by datakid on 25 Nov 2008 06:50 UTC**
ok, so when I read 

https://svn.engagemedia.org/project/plumi-buildout-plone2.5/tags/plumi-0.2.2-final-1/README.txt

I checked my python version, and it was wrong, but then when I looked into the buildout.cfg, 
executable = /path/to/python  already existed
```
executable = /usr/bin/python2.4
```

I checked, and /usr/bin/python.2.4 exists....

**Comment by mgogoulos** [comment]
**Comment by datakid on 25 Nov 2008 06:52 UTC**
ok, needed to have python2.4-dev installed, not just python-dev.

Seems to be past this bug
