### ISSUE TITLE
error while run buildout

### ISSUE THREAD

**Issue by GX76K** [plumi/plumi.app#19]
can someone help me i stuck installasion in this step 

root@vidio:/opt/plumi/plumi.app# ./bin/python bootstrap.py && ./bin/buildout -v
While:
  Initializing.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/tmp/tmppGWQum/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1865, in main
    command, args)
  File "/tmp/tmppGWQum/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 203, in **init**
    data['buildout'].copy(), override, set()))
  File "/tmp/tmppGWQum/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1510, in _open
    downloaded))
  File "/tmp/tmppGWQum/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1466, in _open
    fp = open(filename)
IOError: [Errno 2] No such file or directory: '/opt/plumi/plumi.app/versions.cfg'

**Comment by michaelew** [comment]
Go into plumi.app/versions and copy one of those as plumi.app/versions.cfg and re-run buildout

**Comment by mgogoulos** [comment]
closing, this works now
