### ISSUE TITLE
PloneFTP causing installation issues - cannot import name ftpserver

### ISSUE THREAD

**Issue by bull500** [plumi/plumi.app#22]
Could't load zc.buildout entry point default
from unweb.recipe.ploneftp:
cannot import name ftpserver.
While:
  Installing.
  Getting section ploneftp.
  Initializing section ploneftp.
  Loading zc.buildout recipe entry unweb.recipe.ploneftp:default.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/root/.buildout-cache/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/buildout.py", line 1995, in main
    getattr(buildout, command)(args)
  File "/root/.buildout-cache/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/buildout.py", line 550, in install
    [self[part]['recipe'] for part in install_parts]
  File "/root/.buildout-cache/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/buildout.py", line 1135, in **getitem**
    options._initialize()
  File "/root/.buildout-cache/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/buildout.py", line 1239, in _initialize
    self.initialize()
  File "/root/.buildout-cache/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/buildout.py", line 1245, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/root/.buildout-cache/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/buildout.py", line 1204, in _install_and_load
    req.project_name, group, entry)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2608, in load_entry_point
    return ep.load()
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2268, in load
    return self.resolve()
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2274, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/root/.buildout-cache/eggs/unweb.recipe.ploneftp-0.1-py2.7.egg/unweb/recipe/ploneftp/**init**.py", line 14, in <module>
    from unweb.recipe.ploneftp import zope_ftpd
  File "/root/.buildout-cache/eggs/unweb.recipe.ploneftp-0.1-py2.7.egg/unweb/recipe/ploneftp/zope_ftpd.py", line 39, in <module>
    from pyftpdlib import ftpserver
ImportError: cannot import name ftpserver

**Comment by mgogoulos** [comment]
installations are updated (plus the buildout) now, please check
