### ISSUE TITLE
AttributeError: @@embed_view

### ISSUE THREAD

**Issue by RawNews** [plumi/plumi.app#27]
I've come across this one on a fresh Plumi 4.5.2 deploy:

http://trac.plumi.org/ticket/34

Changed 20 months ago by sam

Reply
Issue 7 is fixed .. 'featured' external videos will no longer break the home page.

Hi,

Plumi 4.5.2 seems to have a problem with "featured" videos.

Is it possible to align the https://github.com/plumi/plumi.app/i code with the changes that fix this issue ?

On a side note: is there anything else already fixed/completed from 4.5.3 which can be brought to 4.5.2 ?

Thanks,

**Comment by mgogoulos** [comment]
Hi, 

I've just updated the docs on https://github.com/plumi/plumi.app. The buildout now runs without problems and this has been tested on Ubuntu 16.04/Debian Jessie/Centos 7. 

Have you tried the buildout now and have received an error with the featured videos? If so what is the operating system? 

Regards

**Comment by krish0005** [comment]
Hi Markos,

Thanks for replying.

I confirm @ RawNews we've been able to test successfully the buildout from a fresh clone of plumi.app and run the Plumi on a Debian 8.6 to start testing it.

```
lsb_release -a

LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:cxx-3.0-amd64:cxx-3.0-noarch:cxx-3.1-amd64:cxx-3.1-noarch:cxx-3.2-amd64:cxx-3.2-noarch:cxx-4.0-amd64:cxx-4.0-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-3.1-amd64:desktop-3.1-noarch:desktop-3.2-amd64:desktop-3.2-noarch:desktop-4.0-amd64:desktop-4.0-noarch:desktop-4.1-amd64:desktop-4.1-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.0-amd64:graphics-3.0-noarch:graphics-3.1-amd64:graphics-3.1-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch:graphics-4.1-amd64:graphics-4.1-noarch:languages-3.2-amd64:languages-3.2-noarch:languages-4.0-amd64:languages-4.0-noarch:languages-4.1-amd64:languages-4.1-noarch:multimedia-3.2-amd64:multimedia-3.2-noarch:multimedia-4.0-amd64:multimedia-4.0-noarch:multimedia-4.1-amd64:multimedia-4.1-noarch:printing-3.2-amd64:printing-3.2-noarch:printing-4.0-amd64:printing-4.0-noarch:printing-4.1-amd64:printing-4.1-noarch:qt4-3.1-amd64:qt4-3.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6
Codename:       jessie

./supervisorctl status
cache                            RUNNING    pid 20555, uptime 0:11:18
nginx                            RUNNING    pid 20584, uptime 0:11:18
ploneftp                         RUNNING    pid 20552, uptime 0:11:18
transcodedaemon                  RUNNING    pid 20551, uptime 0:11:18
uwsgi                            RUNNING    pid 20541, uptime 0:11:20
worker                           RUNNING    pid 20548, uptime 0:11:19
zeo                              RUNNING    pid 20540, uptime 0:11:20
```

This video is currently in **Published** > **Featured** status:

[http://beta.raw-news.net/Members/admin/videos/test-video-01/](url)

But seems to breaks the Home Page as you can see:

[http://beta.raw-news.net/](url)

I can see the following in the logs when the Home is triggered:

```
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/OFS/Traversable.py", line 284, in unrestrictedTraverse
    raise e
AttributeError: @@embed_view
[pid: 20542|app: 0|req: 50/67] 127.0.0.1 () {40 vars in 849 bytes} [Thu Dec 22 11:42:34 2016] GET /VirtualHostBase/http/beta.raw-news.net:80/Plone/VirtualHostRoot/ => generated 0 bytes in 28 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)

==> main-plone-access.log <==
85.115.39.180 - - [22/Dec/2016:11:42:34 +0100] "GET / HTTP/1.1" 503 419 "http://beta.raw-news.net/logged_out" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"

==> uwsgi-stdout---supervisor-hRTYZ9.log <==
[pid: 20543|app: 0|req: 18/68] 127.0.0.1 () {38 vars in 868 bytes} [Thu Dec 22 11:42:36 2016] GET /VirtualHostBase/http/beta.raw-news.net:80/Plone/VirtualHostRoot/Members/admin/videos/test-video-01/ => generated 18661 bytes in 144 msecs (HTTP/1.0 200) 9 headers in 322 bytes (2 switches on core 0)

==> main-plone-access.log <==
85.115.39.180 - - [22/Dec/2016:11:42:37 +0100] "GET /Members/admin/videos/test-video-01/ HTTP/1.1" 200 18661 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"

==> main-error.log <==
2016/12/22 11:42:57 [info] 20586#0: *91 client 85.115.39.180 closed keepalive connection

==> uwsgi-stdout---supervisor-hRTYZ9.log <==
Traceback (most recent call last):
  File "/home/zope/PLUMI/plumi.app/eggs/repoze.retry-1.0-py2.7.egg/repoze/retry/__init__.py", line 90, in __call__
    app_iter = self.application(environ, replace_start_response)
  File "/home/zope/PLUMI/plumi.app/eggs/repoze.tm2-1.0b2-py2.7.egg/repoze/tm/__init__.py", line 24, in __call__
    result = self.application(environ, save_status_and_headers)
  File "/home/zope/PLUMI/plumi.app/eggs/repoze.vhm-0.14-py2.7.egg/repoze/vhm/middleware.py", line 106, in __call__
    return self.application(environ, start_response)
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/ZPublisher/WSGIPublisher.py", line 282, in publish_module
    response = _publish(request, 'Zope2')
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/ZPublisher/WSGIPublisher.py", line 205, in publish
    bind=1,
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/ZPublisher/mapply.py", line 77, in mapply
    if debug is not None: return debug(object,args,context)
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/ZPublisher/Publish.py", line 46, in call_object
    result=apply(object,args) # Type s<cr> to step into published object.
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Products/Five/browser/metaconfigure.py", line 476, in __call__
    return self.index(*args, **kw)
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/zope/PLUMI/plumi.app/eggs/zope.pagetemplate-3.5.2-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 113, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations)()
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 271, in __call__
    self.interpret(self.program)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 888, in do_useMacro
    self.interpret(macro)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 954, in do_defineSlot
    self.interpret(block)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 858, in do_defineMacro
    self.interpret(macro)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 954, in do_defineSlot
    self.interpret(block)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 946, in do_defineSlot
    self.interpret(slot)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 852, in do_condition
    self.interpret(block)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 821, in do_loop_tal
    self.interpret(block)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 742, in do_insertStructure_tal
    structure = self.engine.evaluateStructure(expr)
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Products/PageTemplates/Expressions.py", line 218, in evaluateStructure
    text = super(ZopeContext, self).evaluateStructure(expr)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tales-3.5.2-py2.7.egg/zope/tales/tales.py", line 696, in evaluate
    return expression(self)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tales-3.5.2-py2.7.egg/zope/tales/expressions.py", line 217, in __call__
    return self._eval(econtext)
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Products/PageTemplates/Expressions.py", line 155, in _eval
    return render(ob, econtext.vars)
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Products/PageTemplates/Expressions.py", line 117, in render
    ob = ob()
  File "/home/zope/PLUMI/plumi.app/eggs/plumi.content-4.5-py2.7.egg/plumi/content/browser/brain_rendering.py", line 51, in render_feature_video
    feature_video=True)
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/zope/PLUMI/plumi.app/eggs/zope.pagetemplate-3.5.2-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 113, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations)()
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 271, in __call__
    self.interpret(self.program)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 852, in do_condition
    self.interpret(block)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 531, in do_optTag_tal
    self.no_tag(stuff[-2], stuff[-1])
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 531, in do_optTag_tal
    self.no_tag(stuff[-2], stuff[-1])
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 742, in do_insertStructure_tal
    structure = self.engine.evaluateStructure(expr)
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Products/PageTemplates/Expressions.py", line 218, in evaluateStructure
    text = super(ZopeContext, self).evaluateStructure(expr)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tales-3.5.2-py2.7.egg/zope/tales/tales.py", line 696, in evaluate
    return expression(self)
  File "/home/zope/PLUMI/plumi.app/eggs/zope.tales-3.5.2-py2.7.egg/zope/tales/expressions.py", line 217, in __call__
    return self._eval(econtext)
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Products/PageTemplates/Expressions.py", line 155, in _eval
    return render(ob, econtext.vars)
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Products/PageTemplates/Expressions.py", line 117, in render
    ob = ob()
  File "/home/zope/PLUMI/plumi.app/eggs/plumi.content-4.5-py2.7.egg/plumi/content/browser/brain_rendering.py", line 97, in video_tag
    html = self.__parent__.context.restrictedTraverse(path)(self.request)
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/OFS/Traversable.py", line 316, in restrictedTraverse
    return self.unrestrictedTraverse(path, default, restricted=True)
  File "/home/zope/PLUMI/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/OFS/Traversable.py", line 284, in unrestrictedTraverse
    raise e
AttributeError: @@embed_view
[pid: 20543|app: 0|req: 19/69] 127.0.0.1 () {38 vars in 798 bytes} [Thu Dec 22 11:45:08 2016] GET /VirtualHostBase/http/beta.raw-news.net:80/Plone/VirtualHostRoot/ => generated 0 bytes in 92 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)

==> main-plone-access.log <==
85.115.39.180 - - [22/Dec/2016:11:45:08 +0100] "GET / HTTP/1.1" 503 419 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"

==> main-error.log <==
2016/12/22 11:45:28 [info] 20586#0: *107 client 85.115.39.180 closed keepalive connection

```

**Comment by mgogoulos** [comment]
When I visit http://beta.raw-news.net/Members/admin/videos/test-video-01/ I see the video page but no video there. This error is shown when there's no video "attached" on the video page. Although you've uploaded the video, the dns setting of the video server wasn't set up correctly. 

Visit transcode settings - http://beta.raw-news.net/@@transcode-controlpanel - and set the Daemon address as the correct one (eg videosbeta.raw-news.net ?) The daemon address and the plumi video address are 2 different dns names, but should resolve the same ip, the plumi server ip. I see these two ips are different, so make sure they both resolve to the plumi server and  make the setting on the settings page. 

Make sure you put the same video server name on the www-videoserver-name on site.cfg so that it won't be overwritten next time you run the buildout

So after you make that change, visit the video page as admin and hit retranscode. Once it starts transcoding the file, then the first page will show up well. 

Let me know how it goes.

**Comment by mgogoulos** [comment]
I see your portal and see you've fixed this, so closing the ticket. I'll also change the title so that it can act as a future reference for people having the same issue
