### ISSUE TITLE
ImportError: No module named App.startup

### ISSUE THREAD

**Issue by bull500** [plumi/plumi.app#28]
While doing a fresh install (./bin/python bootstrap.py && ./bin/buildout -v) of Plumi on CentOS i encounter this:

`Generated script '/root/plumi.app/bin/plumisite'.
Installing auto-install-plumisite.
. . . . . . . . . . . 
daemon manager not running
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Zope2/__init__.py", line 51, in app
  File "/root/plumi.app/eggs/Zope2-2.13.15-py2.7.egg/Zope2/__init__.py", line 46, in startup
ImportError: No module named App.startup
While:
  Installing auto-install-plumisite.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/root/plumi.app/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/buildout.py", line 1995, in main
    getattr(buildout, command)(args)
  File "/root/plumi.app/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/buildout.py", line 666, in install
    installed_files = self[part]._call(recipe.install)
  File "/root/plumi.app/eggs/zc.buildout-2.5.3-py2.7.egg/zc/buildout/buildout.py", line 1410, in _call
    return f()
  File "/root/plumi.app/eggs/collective.recipe.cmd-0.8-py2.7.egg/collective/recipe/cmd/__init__.py", line 48, in install
    self.execute()
  File "/root/plumi.app/eggs/collective.recipe.cmd-0.8-py2.7.egg/collective/recipe/cmd/__init__.py", line 61, in execute
    run_commands(cmds, self.shell)
  File "/root/plumi.app/eggs/collective.recipe.cmd-0.8-py2.7.egg/collective/recipe/cmd/__init__.py", line 33, in run_commands
    check_call('%s %s' % (shell, tmpfile), shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'sh /tmp/tmp0EMDc2/run' returned non-zero exit status 1
`

**Comment by artb1sh** [comment]
create user zope & chmod plumi directory

**Comment by artb1sh** [comment]
zope non start root users

**Comment by mgogoulos** [comment]
Haven't seen that error before, did the installation succeed? Does ./bin/supervisord starts all services (./bin/supervisorctl status) and does the portal load after that?

**Comment by bull500** [comment]
@mgogoulos Yes the install succeeded! Thanks to @artb1sh comment i was able to nail down the issue. 
plumi had to be download and as installed as zope user and then ./bin/supervisord should be run as root. 

I have a couple of issue but i dont think they are related specifically to this bug anymore.   
Feel free to close this bug and Thank You for your support

**Comment by mgogoulos** [comment]
Nice! Let us know about the portal you're creating, through URL or a screenshot, we plan to add a section on the plumi blog with plumi powered portals. 

Cheers
