### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by gunawanw9** [plumi/plumi.app#6]
(plumi.app)cloud@GW-Dev:/opt/www/plumi/plumi.app# bin/python setup.py install

```
running install
running bdist_egg
running egg_info
writing requirements to src/plumi.app/plumi.app.egg-info/requires.txt
writing src/plumi.app/plumi.app.egg-info/PKG-INFO
writing namespace_packages to src/plumi.app/plumi.app.egg-info/namespace_package                         s.txt
writing top-level names to src/plumi.app/plumi.app.egg-info/top_level.txt
writing dependency_links to src/plumi.app/plumi.app.egg-info/dependency_links.tx                         t
writing entry points to src/plumi.app/plumi.app.egg-info/entry_points.txt
reading manifest file 'src/plumi.app/plumi.app.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'plumi'
warning: no files found matching 'TODO'
warning: no previously-included files matching '*pyc' found anywhere in distribu                         tion
writing manifest file 'src/plumi.app/plumi.app.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/plumi
creating build/bdist.linux-x86_64/egg/plumi/app
copying build/lib.linux-x86_64-2.7/plumi/app/setuphandlers.py -> build/bdist.lin                         ux-x86_64/egg/plumi/app
copying build/lib.linux-x86_64-2.7/plumi/app/config.py -> build/bdist.linux-x86_                         64/egg/plumi/app
copying build/lib.linux-x86_64-2.7/plumi/app/adapters.py -> build/bdist.linux-x8                         6_64/egg/plumi/app
copying build/lib.linux-x86_64-2.7/plumi/app/__init__.py -> build/bdist.linux-x8                         6_64/egg/plumi/app
copying build/lib.linux-x86_64-2.7/plumi/app/install.py -> build/bdist.linux-x86                         _64/egg/plumi/app
copying build/lib.linux-x86_64-2.7/plumi/app/vocabs.py -> build/bdist.linux-x86_                         64/egg/plumi/app
copying build/lib.linux-x86_64-2.7/plumi/app/translations.py -> build/bdist.linu                         x-x86_64/egg/plumi/app
copying build/lib.linux-x86_64-2.7/plumi/app/member_area.py -> build/bdist.linux                         -x86_64/egg/plumi/app
copying build/lib.linux-x86_64-2.7/plumi/__init__.py -> build/bdist.linux-x86_64                         /egg/plumi
byte-compiling build/bdist.linux-x86_64/egg/plumi/app/setuphandlers.py to setuph                         andlers.pyc
byte-compiling build/bdist.linux-x86_64/egg/plumi/app/config.py to config.pyc
byte-compiling build/bdist.linux-x86_64/egg/plumi/app/adapters.py to adapters.py                         c
byte-compiling build/bdist.linux-x86_64/egg/plumi/app/__init__.py to __init__.py                         c
byte-compiling build/bdist.linux-x86_64/egg/plumi/app/install.py to install.pyc
byte-compiling build/bdist.linux-x86_64/egg/plumi/app/vocabs.py to vocabs.pyc
byte-compiling build/bdist.linux-x86_64/egg/plumi/app/translations.py to transla                         tions.pyc
byte-compiling build/bdist.linux-x86_64/egg/plumi/app/member_area.py to member_a                         rea.pyc
byte-compiling build/bdist.linux-x86_64/egg/plumi/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/plumi.app/plumi.app.egg-info/PKG-INFO -> build/bdist.linux-x86_64/eg                         g/EGG-INFO
copying src/plumi.app/plumi.app.egg-info/SOURCES.txt -> build/bdist.linux-x86_64                         /egg/EGG-INFO
copying src/plumi.app/plumi.app.egg-info/dependency_links.txt -> build/bdist.lin                         ux-x86_64/egg/EGG-INFO
copying src/plumi.app/plumi.app.egg-info/entry_points.txt -> build/bdist.linux-x                         86_64/egg/EGG-INFO
copying src/plumi.app/plumi.app.egg-info/namespace_packages.txt -> build/bdist.l                         inux-x86_64/egg/EGG-INFO
copying src/plumi.app/plumi.app.egg-info/not-zip-safe -> build/bdist.linux-x86_6                         4/egg/EGG-INFO
copying src/plumi.app/plumi.app.egg-info/requires.txt -> build/bdist.linux-x86_6                         4/egg/EGG-INFO
copying src/plumi.app/plumi.app.egg-info/top_level.txt -> build/bdist.linux-x86_                         64/egg/EGG-INFO
creating 'dist/plumi.app-4.5-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg                         ' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing plumi.app-4.5-py2.7.egg
removing '/opt/www/plumi/plumi.app/lib/python2.7/site-packages/plumi.app-4.5-py2                         .7.egg' (and everything under it)
creating /opt/www/plumi/plumi.app/lib/python2.7/site-packages/plumi.app-4.5-py2.                         7.egg
Extracting plumi.app-4.5-py2.7.egg to /opt/www/plumi/plumi.app/lib/python2.7/sit                         e-packages
plumi.app 4.5 is already the active version in easy-install.pth

Installed /opt/www/plumi/plumi.app/lib/python2.7/site-packages/plumi.app-4.5-py2                         .7.egg
Processing dependencies for plumi.app==4.5
Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    """,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/www/plumi/plumi.app/local/lib/python2.7/site-packages/setuptools/command/insta              ll.py", line 67, in run
    self.do_egg_install()
  File "/opt/www/plumi/plumi.app/local/lib/python2.7/site-packages/setuptools/command/insta              ll.py", line 117, in do_egg_install
    cmd.run()
  File "/opt/www/plumi/plumi.app/local/lib/python2.7/site-packages/setuptools/command/easy_              install.py", line 370, in run
    self.easy_install(spec, not self.no_deps)
  File "/opt/www/plumi/plumi.app/local/lib/python2.7/site-packages/setuptools/command/easy_              install.py", line 594, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/opt/www/plumi/plumi.app/local/lib/python2.7/site-packages/setuptools/command/easy_              install.py", line 645, in install_item
    self.process_distribution(spec, dist, deps)
  File "/opt/www/plumi/plumi.app/local/lib/python2.7/site-packages/setuptools/command/easy_              install.py", line 704, in process_distribution
    % e.args
TypeError: not enough arguments for format string
```

is there any clue to solve this issue?

**Comment by mgogoulos** [comment]
installations are updated (plus the buildout) now, please check
