### ISSUE TITLE
Build out Errors out at unittest2 1.1.0 Install

### ISSUE THREAD

**Issue by Listerofsmeg** [plumi/plumi.app#9]
I have had to correct some errors in the build out to get it to work, but I am stuck at the unittest2 install.
I have tried installing unit test manually through apt-get but from what I gather the install script ignores this?

Is there a workaround available for this section of the build out to work? 
I am not particularly Linux savvy and so my ability to identify the problem is limited.

```
Getting required 'unittest2'
 required by em.skin 1.0.
We have no distributions for unittest2 that satisfies 'unittest2'.
Getting distribution for 'unittest2'.
Running easy_install:
/home/plumi/plumi.app/bin/python "-c" "from setuptools.command.easy_install import main;main()" "-mUNxd" "/home/plumi/plumi.app/buildout-cache/eggs/tmp4yhbhl" "-Z" "-q" "/home/plumi/plumi.app/buildout-cache/downloads/dist/unittest2-1.1.0.tar.gz"
path=/home/plumi/plumi.app/buildout-cache/eggs/distribute-0.6.14-py2.7.egg

install_dir /home/plumi/plumi.app/buildout-cache/eggs/tmp4yhbhl
install_dir .
install_dir .

Installed /tmp/easy_install-mzc48A/unittest2-1.1.0/temp/easy_install-HH0ugs/traceback2-1.4.0/pbr-1.8.1-py2.7.egg

Installed /tmp/easy_install-mzc48A/unittest2-1.1.0/traceback2-1.4.0-py2.7.egg
Searching for six>=1.4
Reading http://pypi.python.org/simple/six/
Best match: six 1.10.0
Downloading https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55
Processing six-1.10.0.tar.gz
Running six-1.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-mzc48A/unittest2-1.1.0/temp/easy_install-olptC6/six-1.10.0/egg-dist-tmp-pPaf0i
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1855, in main

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1836, in with_ei_usage

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1859, in <lambda>

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 342, in run

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 562, in easy_install

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 612, in install_item

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 802, in install_eggs

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1079, in build_and_install

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1068, in run_setup

  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 29, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 70, in run
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 31, in <lambda>
  File "setup.py", line 87, in <module>

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 221, in __init__
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 245, in fetch_build_eggs
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 544, in resolve
    will be invoked with each requirement that cannot be met by an
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 786, in best_match
    _sort_dists(dists)
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 798, in obtain

  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 293, in fetch_build_egg
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 582, in easy_install

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 612, in install_item

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 802, in install_eggs

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1079, in build_and_install

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1068, in run_setup

  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 29, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 70, in run
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 31, in <lambda>
  File "setup.py", line 31, in <module>
    "Topic :: Software Development :: Libraries :: Python Modules",
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/bdist_egg.py", line 172, in run
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 171, in run
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1954, in load
    CONTINUE = re.compile(r"\s*\\\s*(#.*)?$").match    # line continuation
ImportError: No module named pbr.pbr_json
An error occurred when trying to install unittest2 1.1.0. Look above this message for any errors that were output by easy_install.
While:
  Installing plone.
  Getting distribution for 'unittest2'.
Error: Couldn't install: unittest2 1.1.0
*********************************************
Overwriting dumped-versions.cfg
*********************************************
```

**Comment by mgogoulos** [comment]
installations are updated (plus the buildout) now, please check
